spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real_state_mp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always